/* AUTH */
export const AUTH_USER_STARTED = 'AUTH_USER_STARTED';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
