/* SPOTS */
export const FETCH_SPOTS_STARTED = 'FETCH_SPOTS_STARTED';
export const FETCH_SPOTS_SUCCESS = 'FETCH_SPOTS_SUCCESS';
export const FETCH_SPOTS_FAILURE = 'FETCH_SPOTS_FAILURE';

export const FETCH_SPOT_STARTED = 'FETCH_SPOT_STARTED';
export const FETCH_SPOT_SUCCESS = 'FETCH_SPOT_SUCCESS';
export const FETCH_SPOT_FAILURE = 'FETCH_SPOT_FAILURE';

export const UPDATE_SPOT_STARTED = 'UPDATE_SPOT_STARTED';
export const UPDATE_SPOT_SUCCESS = 'UPDATE_SPOT_SUCCESS';
export const UPDATE_SPOT_FAILURE = 'UPDATE_SPOT_FAILURE';

export const CREATE_SPOT_STARTED = 'CREATE_SPOT_STARTED';
export const CREATE_SPOT_SUCCESS = 'CREATE_SPOT_SUCCESS';
export const CREATE_SPOT_FAILURE = 'CREATE_SPOT_FAILURE';

export const DELETE_SPOT_STARTED = 'DELETE_SPOT_STARTED';
export const DELETE_SPOT_SUCCESS = 'DELETE_SPOT_SUCCESS';
export const DELETE_SPOT_FAILURE = 'DELETE_SPOT_FAILURE';
