/* API SAMPLE */
export const FETCH_API_SAMPLE_STARTED = 'FETCH_API_SAMPLE_STARTED';
export const FETCH_API_SAMPLE_SUCCESS = 'FETCH_API_SAMPLE_SUCCESS';
export const FETCH_API_SAMPLE_FAILURE = 'FETCH_API_SAMPLE_FAILURE';
